<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_genpact-logo</name>
   <tag></tag>
   <elementGuidId>6adb104b-b58d-4e08-91f0-618353cfe889</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>genpact-logo</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-account[@class=&quot;ng-star-inserted&quot;]/app-login[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;col-xs-12 padding-zero login-body&quot;]/div[@class=&quot;col-xs-12 padding-zero login-user-section&quot;]/div[@class=&quot;col-xs-5 card-details inline-block&quot;]/div[@class=&quot;genpact-logo&quot;]</value>
   </webElementProperties>
</WebElementEntity>
